name: mrz_scanner
description: "MRZ Scanner"
version: 0.0.2

environment:
  sdk: ^3.4.3
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  google_mlkit_commons: ^0.9.0
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # To add assets to your package, add an assets section, like this: